/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nicolás
 */
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

public class DigiGenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DigiGenda.class.getName());

    /**
     * Creates new form DigiGenda
     */
    public DigiGenda() {
        initComponents();
        panelTareas_Contenedor.setVisible(false);
        panelMenu.setVisible(true);
        tablaDatos.setAutoCreateRowSorter(true);
        jLabel1.setVisible(true);
        panelHorario_Contenedor.setVisible(false);
        this.getContentPane().setBackground(new java.awt.Color(153, 204, 255)); // Pon aquí el azul que uses
        this.revalidate();
        this.repaint();
        
        rellenarHorasFijas();
        try {
        cargarHorarioDesdeArchivo();
    } catch (Exception e) {
        System.out.println("Error al cargar datos iniciales: " + e.getMessage());
    }
        jTable1.setRowHeight(33);
        jTable1.setFillsViewportHeight(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelTareas = new javax.swing.JButton();
        panelHorario = new javax.swing.JButton();
        panelTareas_Contenedor = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnNuevaTarea = new javax.swing.JToggleButton();
        btnBorrarTarea = new javax.swing.JButton();
        panelHorario_Contenedor = new javax.swing.JPanel();
        btnVolver2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mi agenda digital");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(98, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(98, 14));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 8, 204, 28));

        panelMenu.setBackground(new java.awt.Color(153, 204, 255));
        panelMenu.setMinimumSize(new java.awt.Dimension(400, 300));
        panelMenu.setPreferredSize(new java.awt.Dimension(400, 300));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTareas.setBackground(new java.awt.Color(51, 153, 255));
        panelTareas.setText("Tareas");
        panelTareas.setMinimumSize(new java.awt.Dimension(182, 240));
        panelTareas.setPreferredSize(new java.awt.Dimension(182, 240));
        panelTareas.addActionListener(this::panelTareasActionPerformed);
        panelMenu.add(panelTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        panelHorario.setBackground(new java.awt.Color(51, 153, 255));
        panelHorario.setText("Horario");
        panelHorario.setPreferredSize(new java.awt.Dimension(182, 240));
        panelHorario.addActionListener(this::panelHorarioActionPerformed);
        panelMenu.add(panelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 390, 260));

        panelTareas_Contenedor.setBackground(new java.awt.Color(153, 204, 255));
        panelTareas_Contenedor.setPreferredSize(new java.awt.Dimension(400, 300));

        btnVolver.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver.setText("->");
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jScrollPane1.setOpaque(false);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Asignatura", "Fecha limite", "¿Hecho?", "Alerta"
            }
        ));
        tablaDatos.setOpaque(false);
        tablaDatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaDatosMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);
        if (tablaDatos.getColumnModel().getColumnCount() > 0) {
            tablaDatos.getColumnModel().getColumn(3).setHeaderValue("¿Hecho?");
        }

        btnNuevaTarea.setBackground(new java.awt.Color(51, 153, 255));
        btnNuevaTarea.setText("+ Nueva tarea");
        btnNuevaTarea.addActionListener(this::btnNuevaTareaActionPerformed);

        btnBorrarTarea.setBackground(new java.awt.Color(51, 153, 255));
        btnBorrarTarea.setText("- Borrar tarea");
        btnBorrarTarea.addActionListener(this::btnBorrarTareaActionPerformed);

        javax.swing.GroupLayout panelTareas_ContenedorLayout = new javax.swing.GroupLayout(panelTareas_Contenedor);
        panelTareas_Contenedor.setLayout(panelTareas_ContenedorLayout);
        panelTareas_ContenedorLayout.setHorizontalGroup(
            panelTareas_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareas_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareas_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelTareas_ContenedorLayout.createSequentialGroup()
                        .addComponent(btnNuevaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTareas_ContenedorLayout.setVerticalGroup(
            panelTareas_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareas_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareas_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaTarea)
                    .addComponent(btnBorrarTarea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelTareas_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelHorario_Contenedor.setBackground(new java.awt.Color(153, 204, 255));
        panelHorario_Contenedor.setPreferredSize(new java.awt.Dimension(400, 300));

        btnVolver2.setBackground(new java.awt.Color(255, 102, 102));
        btnVolver2.setText("->");
        btnVolver2.addActionListener(this::btnVolver2ActionPerformed);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(375, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "HORAS", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setPreferredSize(new java.awt.Dimension(375, 80));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panelHorario_ContenedorLayout = new javax.swing.GroupLayout(panelHorario_Contenedor);
        panelHorario_Contenedor.setLayout(panelHorario_ContenedorLayout);
        panelHorario_ContenedorLayout.setHorizontalGroup(
            panelHorario_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHorario_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHorario_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHorario_ContenedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelHorario_ContenedorLayout.setVerticalGroup(
            panelHorario_ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHorario_ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelHorario_Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelTareasActionPerformed
        // TODO add your handling code here:
        panelMenu.setVisible(false);
        panelHorario.setVisible(false);
        panelTareas.setVisible(true);
        panelTareas_Contenedor.setVisible(true);
        jLabel1.setVisible(false);
        
        cargarDatosTareas();
    }//GEN-LAST:event_panelTareasActionPerformed

    private void panelHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelHorarioActionPerformed
        // TODO add your handling code here:
        panelMenu.setVisible(false);
        panelTareas.setVisible(false);
        panelHorario.setVisible(true);
        btnVolver2.setVisible(true);
        panelHorario_Contenedor.setVisible(true);
    }//GEN-LAST:event_panelHorarioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        panelHorario_Contenedor.setVisible(false);
        panelTareas_Contenedor.setVisible(false);
        panelMenu.setVisible(true);
        panelHorario.setVisible(true);
        jLabel1.setVisible(true);
    
    // En lugar de getWidth(), ponemos los números que tú mismo configuraste
    this.setSize(420, 350);
    
    panelMenu.setSize(420, 350);
    panelMenu.setBounds(0, 0, 420, 350);
   
    this.revalidate();
    this.repaint();
    
    this.getContentPane().setBackground(new java.awt.Color(153, 204, 255)); // Pon aquí el azul que uses
    this.revalidate();
    this.repaint(); 
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tablaDatosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDatosMouseMoved

    private void btnNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTareaActionPerformed
        // TODO add your handling code here:
    String[] opciones = {"Tarea", "Examen"};
    javax.swing.JComboBox<String> cbTipo = new javax.swing.JComboBox<>(opciones);
    javax.swing.JTextField txtAsignatura = new javax.swing.JTextField();
    javax.swing.JTextField txtFecha = new javax.swing.JTextField("2026-05-10"); // Formato sugerido

    Object[] message = {
        "Tipo:", cbTipo,
        "Asignatura:", txtAsignatura,
        "Fecha (AAAA-MM-DD):", txtFecha,
    };

    int option = javax.swing.JOptionPane.showConfirmDialog(null, message, "Añadir Nueva Tarea", javax.swing.JOptionPane.OK_CANCEL_OPTION);

    if (option == javax.swing.JOptionPane.OK_OPTION) {
        String tipo = cbTipo.getSelectedItem().toString();
        String asig = txtAsignatura.getText();
        String fecha = txtFecha.getText();
        String hecho = (tipo.equals("Tarea")) ? "pendiente" : "---";
    
        // Guardamos en el archivo
        guardarEnArchivo(tipo + "," + asig + "," + fecha + "," + hecho);
        
    }
    }//GEN-LAST:event_btnNuevaTareaActionPerformed

    private void btnBorrarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTareaActionPerformed
        // TODO add your handling code here:
        int fila = tablaDatos.getSelectedRow();
    
    if (fila != -1) {
        // 1. Sacamos el nombre de la asignatura de la fila seleccionada
        String asignaturaABorrar = tablaDatos.getValueAt(fila, 1).toString();
        
        // 2. Lógica de borrado directamente aquí dentro
        java.util.List<String> lineasParaGuardar = new java.util.ArrayList<>();
        
        try {
            // Leemos el archivo
            BufferedReader br = new BufferedReader(new FileReader("datos.txt"));
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Comparamos: si no es la asignatura seleccionada, la guardamos
                if (datos.length > 1 && !datos[1].equals(asignaturaABorrar)) {
                    lineasParaGuardar.add(linea);
                }
            }
            br.close();

            // Escribimos el archivo de nuevo
            PrintWriter pw = new PrintWriter(new FileWriter("datos.txt"));
            for (String l : lineasParaGuardar) {
                pw.println(l);
            }
            pw.close();

            // 3. Actualizamos la tabla para que desaparezca visualmente
            cargarDatosTareas();
            javax.swing.JOptionPane.showMessageDialog(this, "Tarea eliminada correctamente.");

        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al acceder al archivo: " + e.getMessage());
        }
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila primero.");
    }

    }//GEN-LAST:event_btnBorrarTareaActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        // TODO add your handling code here:
        panelHorario_Contenedor.setVisible(false);
        panelTareas_Contenedor.setVisible(false);
        panelMenu.setVisible(true);
        panelHorario.setVisible(true);
        jLabel1.setVisible(true);
        panelTareas.setVisible(true);
    
    // En lugar de getWidth(), ponemos los números que tú mismo configuraste
    this.setSize(420, 350);
    
    panelMenu.setSize(420, 350);
    panelMenu.setBounds(0, 0, 420, 350);
   
    this.revalidate();
    this.repaint();
    
    this.getContentPane().setBackground(new java.awt.Color(153, 204, 255)); // Pon aquí el azul que uses
    this.revalidate();
    this.repaint();
    }//GEN-LAST:event_btnVolver2ActionPerformed
public void guardarEnArchivo(String lineaNueva) {
    try (BufferedWriter bw = new BufferedWriter(new FileWriter("datos.txt", true))) {
        bw.write(lineaNueva);
        bw.newLine(); // Esto hace que la próxima tarea se escriba en una línea nueva
        bw.close();
        
        // Refrescamos la tabla automáticamente para ver la nueva tarea
        cargarDatosTareas();
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Tarea guardada con éxito!");
    } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
    }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DigiGenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarTarea;
    private javax.swing.JToggleButton btnNuevaTarea;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton panelHorario;
    private javax.swing.JPanel panelHorario_Contenedor;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton panelTareas;
    private javax.swing.JPanel panelTareas_Contenedor;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables


// ... dentro de la clase ...

public void cargarDatosTareas() {
DefaultTableModel modelo = (DefaultTableModel) tablaDatos.getModel();
    modelo.setRowCount(0); // Limpiamos la tabla

    try (BufferedReader br = new BufferedReader(new FileReader("datos.txt"))) {
        String linea;
        // Solo un bucle while para leer línea por línea
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length >= 3) {
                // Creamos el array de 4 espacios (los que tienes ahora en el diseño)
                Object[] filaConAlerta = new Object[4];
                filaConAlerta[0] = datos[0].trim(); // Tipo
                filaConAlerta[1] = datos[1].trim(); // Asignatura
                filaConAlerta[2] = datos[2].trim(); // Fecha

                // Lógica de Alerta automática
                try {
                    LocalDate fechaTarea = LocalDate.parse(datos[2].trim());
                    LocalDate hoy = LocalDate.now();
                    long diasRestantes = ChronoUnit.DAYS.between(hoy, fechaTarea);

                    if (diasRestantes <= 4 && diasRestantes >= 0) {
                        filaConAlerta[3] = "¡URGENTE!";
                    } else if (diasRestantes < 0) {
                        filaConAlerta[3] = "CADUCADO";
                    } else {
                        filaConAlerta[3] = "---";
                    }
                } catch (Exception e) {
                    filaConAlerta[3] = "Error fecha";
                }

                modelo.addRow(filaConAlerta); // Añadimos la fila a la tabla
            }
        }
    } catch (Exception e) {
        System.out.println("Error al leer datos.txt: " + e.getMessage());
    }
    
    // Aplicamos tu código de ordenación que tenías antes
    TableRowSorter sorter = new TableRowSorter(modelo);
    tablaDatos.setRowSorter(sorter);
    java.util.List<RowSorter.SortKey> sortKeys = new java.util.ArrayList<>();
    sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
    sorter.setSortKeys(sortKeys);
    sorter.sort();
}
public void cargarHorarioDesdeArchivo() {
    File archivo = new File("horario.txt");
    if (!archivo.exists()) return; // Si no hay archivo, no hacemos nada

    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            if (linea.trim().isEmpty()) continue; // Saltamos líneas vacías
            
            String[] datos = linea.split(",");
            if (datos.length >= 3) {
                String dia = datos[0].trim();
                String hora = datos[1].trim();
                String asignatura = datos[2].trim();

                int f = obtenerFilaPorHora(hora);
                int c = obtenerColumnaPorDia(dia);

                if (f != -1 && c != -1) {
                    jTable1.setValueAt(asignatura, f, c);
                }
            }
        }
    } catch (Exception e) {
        // Esto hará que el error salga en la consola de abajo, pero la app abrirá
        System.err.println("Error silencioso al cargar: " + e.getMessage());
    }
}

// Funciones auxiliares para situar los datos
private int obtenerColumnaPorDia(String dia) {
    switch (dia.toUpperCase()) {
        case "LUNES": return 1;
        case "MARTES": return 2;
        case "MIERCOLES": return 3;
        case "JUEVES": return 4;
        case "VIERNES": return 5;
        default: return -1;
    }
}

private int obtenerFilaPorHora(String hora) {
    // Aquí comparas con las horas exactas de tu archivo .txt
    if (hora.contains("08:30")) return 0;
    if (hora.contains("09:25")) return 1;
    if (hora.contains("10:20")) return 2;
    if (hora.contains("11:15")) return 3; // RECREO
    if (hora.contains("11:45")) return 4;
    if (hora.contains("12:40")) return 5;
    if (hora.contains("13:35")) return 6;
    return -1;
}
private void rellenarHorasFijas() {
    // Usamos el nombre jTable1 que es el que sale en tu captura image_3584ba
    String[] horas = {"08:30", "09:25", "10:20", "11:15", "11:45", "12:40", "13:35"};
    
    for (int i = 0; i < horas.length; i++) {
        if (i < jTable1.getRowCount()) {
            jTable1.setValueAt(horas[i], i, 0);
        }
    }
}
}



